version: '3.8'

services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    restart: always
    networks:
      - default
      - dokploy-network  # Dokploy ağına bağlantı için eklendi
    # Traefik yönlendirme yapacağı için doğrudan port açmaya gerek yok
    # ports:
    #   - "80:80"
    #   - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - pelican-data:/pelican-data
      - pelican-logs:/var/www/html/storage/logs
    environment:
      # Panel ortam değişkenleri
      APP_URL: "${APP_URL:-https://panel.example.com}"  # Domain adınızla değiştirin
      ADMIN_EMAIL: "${ADMIN_EMAIL:-admin@example.com}"  # E-posta adresinizle değiştirin
      APP_DEBUG: "false"
      APP_ENV: "production"
      XDG_DATA_HOME: /pelican-data

      # Mail ortam değişkenleri
      MAIL_DRIVER: "log"
      # MAIL_HOST: ""
      # MAIL_PORT: ""
      # MAIL_FROM: ""
      # MAIL_USERNAME: ""
      # MAIL_PASSWORD: ""
      # MAIL_SCHEME: ""

      # Caddy'yi devre dışı bırak, Traefik yönlendirme yapacak
      SKIP_CADDY: "true"

    # Dokploy Traefik etiketleri
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`${APP_URL:-panel.example.com}`)"
      - "traefik.http.routers.panel.entrypoints=websecure"
      - "traefik.http.routers.panel.tls=true"
      - "traefik.http.routers.panel.tls.certresolver=letsencrypt"
      - "traefik.http.services.panel.loadbalancer.server.port=9000"  # Caddy'yi atladığımız için PHP-FPM portu

volumes:
  pelican-data:
  pelican-logs:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  dokploy-network:
    external: true  # Dokploy'un harici ağını kullan
