################################
## Panel Database Secret
#################################
{{- $host:=  .Values.mariadb.nameOverride | default (printf "%s-%s.%s" .Release.Name "mariadb" .Release.Namespace) }}
{{- $port := .Values.ports.mariadb | toString }}
{{- $database := .Values.mariadb.primary.name}}

{{- if not .Values.mariadb.dbSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panel.fullname" . }}-mariadb-connection
  labels:
    tier: panel
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- with .Values.mariadb.dbConnection }}
  connection: {{ urlJoin (dict "scheme" .protocol "userinfo" (printf "%s:%s" (.user | urlquery) (.pass | urlquery) ) "host" (printf "%s:%s" $host $port) "path" (printf "/%s" $database) ) | b64enc | quote }}
  {{- end }}
{{- end }}
