name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ui:
    name: UI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: |
            bcmath
            curl
            gd
            mbstring
            openssl
            pdo
            tokenizer
            xml
            zip
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --no-autoloader --no-scripts --no-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build