name: CLA Assistant

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  cla-assistant:
    name: CLA Assistant
    runs-on: ubuntu-latest
    steps:
      - name: Run CLA Assistant
        if: >
          github.event.comment.body == 'recheck' || 
          github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || 
          github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: version1/cla.json
          path-to-document: https://github.com/pelican-dev/panel/blob/main/contributor_license_agreement.md
          branch: main
          allowlist: dependabot[bot]
          remote-organization-name: pelican-dev
          remote-repository-name: cla-signatures