name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: |
            bcmath
            curl
            gd
            mbstring
            mysql
            openssl
            pdo
            tokenizer
            xml
            zip
          tools: composer:v2

      - name: Install PHP Dependencies
        run: composer install --no-interaction --no-progress --no-autoloader --no-scripts --no-dev

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install JS Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Assets
        run: yarn build

      - name: Create Release Branch and Bump Version
        env:
          REF: ${{ github.ref }}
        run: |
          BRANCH=release/${REF:10}
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b $BRANCH
          sed -i "s/    'version' => 'canary',/    'version' => '${REF:11}',/" config/app.php
          git add config/app.php
          git commit -m "ci(release): bump version"
          git push -u origin $BRANCH

      - name: Create Release Archive
        run: |
          rm -rf node_modules vendor tests CODE_OF_CONDUCT.md CONTRIBUTING.md phpunit.xml shell.nix
          tar -czf panel.tar.gz * .env.example

      - name: Create Checksum
        run: sha256sum panel.tar.gz > checksum.txt

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          files: |
            panel.tar.gz
            checksum.txt